# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9746282457ee4267c280b77e7c70cb4470d4044c64870cd905f7c095ff8dc244bfc31bd64e04725283209088d70ec9e613033e539cf27aec046c46a6676f13

test:
  secret_key_base: 15c3f5bdf06271a6994095fdf59d2ab36a6c9fb85e579d022b49136bbad5ce97e84dbbff220d6740f86eb8c72d1b926cc8b5263379f3b59d5982fb14350c537e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
